# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatabaseEntryValueObject")

model_instance <- DatabaseEntryValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("externalDatabase", {
  # tests for the property `externalDatabase` (ExternalDatabaseValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`externalDatabase`, "EXPECTED_RESULT")
})
