# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SimpleSVDValueObject")

model_instance <- SimpleSVDValueObject$new()

test_that("bioMaterialIds", {
  # tests for the property `bioMaterialIds` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioMaterialIds`, "EXPECTED_RESULT")
})

test_that("variances", {
  # tests for the property `variances` (array[numeric])

  # uncomment below to test the property
  #expect_equal(model.instance$`variances`, "EXPECTED_RESULT")
})

test_that("getvMatrix", {
  # tests for the property `getvMatrix` (DoubleMatrixLongInteger)

  # uncomment below to test the property
  #expect_equal(model.instance$`getvMatrix`, "EXPECTED_RESULT")
})
