# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeneOntologyTermValueObject")

model_instance <- GeneOntologyTermValueObject$new()

test_that("goId", {
  # tests for the property `goId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`goId`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("comment", {
  # tests for the property `comment` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`comment`, "EXPECTED_RESULT")
})

test_that("localName", {
  # tests for the property `localName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`localName`, "EXPECTED_RESULT")
})

test_that("term", {
  # tests for the property `term` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`term`, "EXPECTED_RESULT")
})

test_that("obsolete", {
  # tests for the property `obsolete` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`obsolete`, "EXPECTED_RESULT")
})
