# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CurationDetails")

model_instance <- CurationDetails$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("lastUpdated", {
  # tests for the property `lastUpdated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastUpdated`, "EXPECTED_RESULT")
})

test_that("lastNeedsAttentionEvent", {
  # tests for the property `lastNeedsAttentionEvent` (AuditEvent)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastNeedsAttentionEvent`, "EXPECTED_RESULT")
})

test_that("needsAttention", {
  # tests for the property `needsAttention` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`needsAttention`, "EXPECTED_RESULT")
})

test_that("lastTroubledEvent", {
  # tests for the property `lastTroubledEvent` (AuditEvent)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastTroubledEvent`, "EXPECTED_RESULT")
})

test_that("troubled", {
  # tests for the property `troubled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`troubled`, "EXPECTED_RESULT")
})

test_that("lastNoteUpdateEvent", {
  # tests for the property `lastNoteUpdateEvent` (AuditEvent)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastNoteUpdateEvent`, "EXPECTED_RESULT")
})

test_that("curationNote", {
  # tests for the property `curationNote` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`curationNote`, "EXPECTED_RESULT")
})
