# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatabaseEntry")

model_instance <- DatabaseEntry$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("accessionVersion", {
  # tests for the property `accessionVersion` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accessionVersion`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("externalDatabase", {
  # tests for the property `externalDatabase` (ExternalDatabase)

  # uncomment below to test the property
  #expect_equal(model.instance$`externalDatabase`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})
