# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponseDataObjectSetAnnotationValueObject")

model_instance <- ResponseDataObjectSetAnnotationValueObject$new()

test_that("data", {
  # tests for the property `data` (set[AnnotationValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
