# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PhysicalLocation")

model_instance <- PhysicalLocation$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("chromosome", {
  # tests for the property `chromosome` (Chromosome)

  # uncomment below to test the property
  #expect_equal(model.instance$`chromosome`, "EXPECTED_RESULT")
})

test_that("nucleotide", {
  # tests for the property `nucleotide` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotide`, "EXPECTED_RESULT")
})

test_that("nucleotideLength", {
  # tests for the property `nucleotideLength` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotideLength`, "EXPECTED_RESULT")
})

test_that("strand", {
  # tests for the property `strand` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strand`, "EXPECTED_RESULT")
})

test_that("bin", {
  # tests for the property `bin` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`bin`, "EXPECTED_RESULT")
})
