# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuditEvent")

model_instance <- AuditEvent$new()

test_that("action", {
  # tests for the property `action` (AuditAction)

  # uncomment below to test the property
  #expect_equal(model.instance$`action`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("detail", {
  # tests for the property `detail` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`detail`, "EXPECTED_RESULT")
})

test_that("eventType", {
  # tests for the property `eventType` (AuditEventType)

  # uncomment below to test the property
  #expect_equal(model.instance$`eventType`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("note", {
  # tests for the property `note` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})

test_that("performer", {
  # tests for the property `performer` (User)

  # uncomment below to test the property
  #expect_equal(model.instance$`performer`, "EXPECTED_RESULT")
})
