# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeneValueObject")

model_instance <- GeneValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("associatedExperimentCount", {
  # tests for the property `associatedExperimentCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`associatedExperimentCount`, "EXPECTED_RESULT")
})

test_that("compositeSequenceCount", {
  # tests for the property `compositeSequenceCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`compositeSequenceCount`, "EXPECTED_RESULT")
})

test_that("geneSets", {
  # tests for the property `geneSets` (array[GeneSetValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`geneSets`, "EXPECTED_RESULT")
})

test_that("homologues", {
  # tests for the property `homologues` (array[GeneValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`homologues`, "EXPECTED_RESULT")
})

test_that("isQuery", {
  # tests for the property `isQuery` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isQuery`, "EXPECTED_RESULT")
})

test_that("multifunctionalityRank", {
  # tests for the property `multifunctionalityRank` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`multifunctionalityRank`, "EXPECTED_RESULT")
})

test_that("ncbiId", {
  # tests for the property `ncbiId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ncbiId`, "EXPECTED_RESULT")
})

test_that("ensemblId", {
  # tests for the property `ensemblId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ensemblId`, "EXPECTED_RESULT")
})

test_that("nodeDegreeNegRanks", {
  # tests for the property `nodeDegreeNegRanks` (array[numeric])

  # uncomment below to test the property
  #expect_equal(model.instance$`nodeDegreeNegRanks`, "EXPECTED_RESULT")
})

test_that("nodeDegreePosRanks", {
  # tests for the property `nodeDegreePosRanks` (array[numeric])

  # uncomment below to test the property
  #expect_equal(model.instance$`nodeDegreePosRanks`, "EXPECTED_RESULT")
})

test_that("nodeDegreesNeg", {
  # tests for the property `nodeDegreesNeg` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`nodeDegreesNeg`, "EXPECTED_RESULT")
})

test_that("nodeDegreesPos", {
  # tests for the property `nodeDegreesPos` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`nodeDegreesPos`, "EXPECTED_RESULT")
})

test_that("numGoTerms", {
  # tests for the property `numGoTerms` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numGoTerms`, "EXPECTED_RESULT")
})

test_that("officialName", {
  # tests for the property `officialName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`officialName`, "EXPECTED_RESULT")
})

test_that("officialSymbol", {
  # tests for the property `officialSymbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`officialSymbol`, "EXPECTED_RESULT")
})

test_that("phenotypes", {
  # tests for the property `phenotypes` (array[CharacteristicValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`phenotypes`, "EXPECTED_RESULT")
})

test_that("platformCount", {
  # tests for the property `platformCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`platformCount`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("taxonCommonName", {
  # tests for the property `taxonCommonName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonCommonName`, "EXPECTED_RESULT")
})

test_that("taxonId", {
  # tests for the property `taxonId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonId`, "EXPECTED_RESULT")
})

test_that("taxonScientificName", {
  # tests for the property `taxonScientificName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonScientificName`, "EXPECTED_RESULT")
})
