# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeeqValueObject")

model_instance <- GeeqValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("publicQualityScore", {
  # tests for the property `publicQualityScore` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`publicQualityScore`, "EXPECTED_RESULT")
})

test_that("publicSuitabilityScore", {
  # tests for the property `publicSuitabilityScore` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`publicSuitabilityScore`, "EXPECTED_RESULT")
})

test_that("getsScorePublication", {
  # tests for the property `getsScorePublication` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScorePublication`, "EXPECTED_RESULT")
})

test_that("getsScorePlatformAmount", {
  # tests for the property `getsScorePlatformAmount` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScorePlatformAmount`, "EXPECTED_RESULT")
})

test_that("getsScorePlatformsTechMulti", {
  # tests for the property `getsScorePlatformsTechMulti` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScorePlatformsTechMulti`, "EXPECTED_RESULT")
})

test_that("getsScoreAvgPlatformPopularity", {
  # tests for the property `getsScoreAvgPlatformPopularity` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScoreAvgPlatformPopularity`, "EXPECTED_RESULT")
})

test_that("getsScoreAvgPlatformSize", {
  # tests for the property `getsScoreAvgPlatformSize` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScoreAvgPlatformSize`, "EXPECTED_RESULT")
})

test_that("getsScoreSampleSize", {
  # tests for the property `getsScoreSampleSize` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScoreSampleSize`, "EXPECTED_RESULT")
})

test_that("getsScoreRawData", {
  # tests for the property `getsScoreRawData` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScoreRawData`, "EXPECTED_RESULT")
})

test_that("getsScoreMissingValues", {
  # tests for the property `getsScoreMissingValues` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getsScoreMissingValues`, "EXPECTED_RESULT")
})

test_that("getqScoreOutliers", {
  # tests for the property `getqScoreOutliers` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScoreOutliers`, "EXPECTED_RESULT")
})

test_that("getqScoreSampleMeanCorrelation", {
  # tests for the property `getqScoreSampleMeanCorrelation` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScoreSampleMeanCorrelation`, "EXPECTED_RESULT")
})

test_that("getqScoreSampleMedianCorrelation", {
  # tests for the property `getqScoreSampleMedianCorrelation` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScoreSampleMedianCorrelation`, "EXPECTED_RESULT")
})

test_that("getqScoreSampleCorrelationVariance", {
  # tests for the property `getqScoreSampleCorrelationVariance` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScoreSampleCorrelationVariance`, "EXPECTED_RESULT")
})

test_that("getqScorePlatformsTech", {
  # tests for the property `getqScorePlatformsTech` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScorePlatformsTech`, "EXPECTED_RESULT")
})

test_that("getqScoreReplicates", {
  # tests for the property `getqScoreReplicates` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScoreReplicates`, "EXPECTED_RESULT")
})

test_that("getqScoreBatchInfo", {
  # tests for the property `getqScoreBatchInfo` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScoreBatchInfo`, "EXPECTED_RESULT")
})

test_that("getqScorePublicBatchEffect", {
  # tests for the property `getqScorePublicBatchEffect` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScorePublicBatchEffect`, "EXPECTED_RESULT")
})

test_that("getqScorePublicBatchConfound", {
  # tests for the property `getqScorePublicBatchConfound` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`getqScorePublicBatchConfound`, "EXPECTED_RESULT")
})

test_that("noVectors", {
  # tests for the property `noVectors` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`noVectors`, "EXPECTED_RESULT")
})

test_that("corrMatIssues", {
  # tests for the property `corrMatIssues` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`corrMatIssues`, "EXPECTED_RESULT")
})

test_that("replicatesIssues", {
  # tests for the property `replicatesIssues` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`replicatesIssues`, "EXPECTED_RESULT")
})

test_that("batchCorrected", {
  # tests for the property `batchCorrected` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`batchCorrected`, "EXPECTED_RESULT")
})
