# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PhenotypeMappingType")

model_instance <- PhenotypeMappingType$new()

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("mutable", {
  # tests for the property `mutable` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`mutable`, "EXPECTED_RESULT")
})
