# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnnotationValueObject")

model_instance <- AnnotationValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("classUri", {
  # tests for the property `classUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`classUri`, "EXPECTED_RESULT")
})

test_that("className", {
  # tests for the property `className` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`className`, "EXPECTED_RESULT")
})

test_that("termUri", {
  # tests for the property `termUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`termUri`, "EXPECTED_RESULT")
})

test_that("termName", {
  # tests for the property `termName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`termName`, "EXPECTED_RESULT")
})

test_that("parentName", {
  # tests for the property `parentName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentName`, "EXPECTED_RESULT")
})

test_that("parentDescription", {
  # tests for the property `parentDescription` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentDescription`, "EXPECTED_RESULT")
})

test_that("parentLink", {
  # tests for the property `parentLink` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentLink`, "EXPECTED_RESULT")
})

test_that("parentOfParentName", {
  # tests for the property `parentOfParentName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentOfParentName`, "EXPECTED_RESULT")
})

test_that("parentOfParentDescription", {
  # tests for the property `parentOfParentDescription` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentOfParentDescription`, "EXPECTED_RESULT")
})

test_that("parentOfParentLink", {
  # tests for the property `parentOfParentLink` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentOfParentLink`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("evidenceCode", {
  # tests for the property `evidenceCode` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`evidenceCode`, "EXPECTED_RESULT")
})

test_that("objectClass", {
  # tests for the property `objectClass` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectClass`, "EXPECTED_RESULT")
})
