# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CharacteristicBasicValueObject")

model_instance <- CharacteristicBasicValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("valueUri", {
  # tests for the property `valueUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`valueUri`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("categoryUri", {
  # tests for the property `categoryUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`categoryUri`, "EXPECTED_RESULT")
})
