# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeneElementExpressionsValueObject")

model_instance <- GeneElementExpressionsValueObject$new()

test_that("geneOfficialSymbol", {
  # tests for the property `geneOfficialSymbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`geneOfficialSymbol`, "EXPECTED_RESULT")
})

test_that("geneNcbiId", {
  # tests for the property `geneNcbiId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`geneNcbiId`, "EXPECTED_RESULT")
})

test_that("vectors", {
  # tests for the property `vectors` (array[VectorElementValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`vectors`, "EXPECTED_RESULT")
})
