# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SearchSettingsValueObject")

model_instance <- SearchSettingsValueObject$new()

test_that("query", {
  # tests for the property `query` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`query`, "EXPECTED_RESULT")
})

test_that("resultTypes", {
  # tests for the property `resultTypes` (set[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`resultTypes`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (TaxonValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("platform", {
  # tests for the property `platform` (ArrayDesignValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`platform`, "EXPECTED_RESULT")
})

test_that("maxResults", {
  # tests for the property `maxResults` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxResults`, "EXPECTED_RESULT")
})
