# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Characteristic")

model_instance <- Characteristic$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("categoryUri", {
  # tests for the property `categoryUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`categoryUri`, "EXPECTED_RESULT")
})

test_that("evidenceCode", {
  # tests for the property `evidenceCode` (GOEvidenceCode)

  # uncomment below to test the property
  #expect_equal(model.instance$`evidenceCode`, "EXPECTED_RESULT")
})

test_that("originalValue", {
  # tests for the property `originalValue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`originalValue`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("valueUri", {
  # tests for the property `valueUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`valueUri`, "EXPECTED_RESULT")
})
