# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponseErrorObject")

model_instance <- ResponseErrorObject$new()

test_that("error", {
  # tests for the property `error` (WellComposedErrorBody)

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("apiVersion", {
  # tests for the property `apiVersion` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`apiVersion`, "EXPECTED_RESULT")
})
