# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BibliographicReference")

model_instance <- BibliographicReference$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("authorList", {
  # tests for the property `authorList` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`authorList`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("publisher", {
  # tests for the property `publisher` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`publisher`, "EXPECTED_RESULT")
})

test_that("editor", {
  # tests for the property `editor` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`editor`, "EXPECTED_RESULT")
})

test_that("volume", {
  # tests for the property `volume` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`volume`, "EXPECTED_RESULT")
})

test_that("issue", {
  # tests for the property `issue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`issue`, "EXPECTED_RESULT")
})

test_that("pages", {
  # tests for the property `pages` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`pages`, "EXPECTED_RESULT")
})

test_that("publication", {
  # tests for the property `publication` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`publication`, "EXPECTED_RESULT")
})

test_that("fullTextUri", {
  # tests for the property `fullTextUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fullTextUri`, "EXPECTED_RESULT")
})

test_that("abstractText", {
  # tests for the property `abstractText` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`abstractText`, "EXPECTED_RESULT")
})

test_that("citation", {
  # tests for the property `citation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`citation`, "EXPECTED_RESULT")
})

test_that("publicationDate", {
  # tests for the property `publicationDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`publicationDate`, "EXPECTED_RESULT")
})

test_that("annotatedAbstract", {
  # tests for the property `annotatedAbstract` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotatedAbstract`, "EXPECTED_RESULT")
})

test_that("pubAccession", {
  # tests for the property `pubAccession` (DatabaseEntry)

  # uncomment below to test the property
  #expect_equal(model.instance$`pubAccession`, "EXPECTED_RESULT")
})

test_that("retracted", {
  # tests for the property `retracted` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`retracted`, "EXPECTED_RESULT")
})

test_that("annotations", {
  # tests for the property `annotations` (set[Characteristic])

  # uncomment below to test the property
  #expect_equal(model.instance$`annotations`, "EXPECTED_RESULT")
})

test_that("meshTerms", {
  # tests for the property `meshTerms` (set[MedicalSubjectHeading])

  # uncomment below to test the property
  #expect_equal(model.instance$`meshTerms`, "EXPECTED_RESULT")
})

test_that("keywords", {
  # tests for the property `keywords` (set[Keyword])

  # uncomment below to test the property
  #expect_equal(model.instance$`keywords`, "EXPECTED_RESULT")
})

test_that("chemicals", {
  # tests for the property `chemicals` (set[Compound])

  # uncomment below to test the property
  #expect_equal(model.instance$`chemicals`, "EXPECTED_RESULT")
})
