# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CompositeSequence")

model_instance <- CompositeSequence$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("biologicalCharacteristic", {
  # tests for the property `biologicalCharacteristic` (BioSequence)

  # uncomment below to test the property
  #expect_equal(model.instance$`biologicalCharacteristic`, "EXPECTED_RESULT")
})

test_that("arrayDesign", {
  # tests for the property `arrayDesign` (ArrayDesign)

  # uncomment below to test the property
  #expect_equal(model.instance$`arrayDesign`, "EXPECTED_RESULT")
})
