# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeneMappingSummary")

model_instance <- GeneMappingSummary$new()

test_that("geneProductIdMap", {
  # tests for the property `geneProductIdMap` (map(GeneProductValueObject))

  # uncomment below to test the property
  #expect_equal(model.instance$`geneProductIdMap`, "EXPECTED_RESULT")
})

test_that("geneProductIdGeneMap", {
  # tests for the property `geneProductIdGeneMap` (map(GeneValueObject))

  # uncomment below to test the property
  #expect_equal(model.instance$`geneProductIdGeneMap`, "EXPECTED_RESULT")
})

test_that("blatResult", {
  # tests for the property `blatResult` (BlatResultValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`blatResult`, "EXPECTED_RESULT")
})

test_that("geneProductMap", {
  # tests for the property `geneProductMap` (map(GeneValueObject))

  # uncomment below to test the property
  #expect_equal(model.instance$`geneProductMap`, "EXPECTED_RESULT")
})

test_that("compositeSequence", {
  # tests for the property `compositeSequence` (CompositeSequenceValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`compositeSequence`, "EXPECTED_RESULT")
})

test_that("identity", {
  # tests for the property `identity` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`identity`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("blatResultId", {
  # tests for the property `blatResultId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`blatResultId`, "EXPECTED_RESULT")
})

test_that("geneProducts", {
  # tests for the property `geneProducts` (array[GeneProductValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`geneProducts`, "EXPECTED_RESULT")
})
