# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Multifunctionality")

model_instance <- Multifunctionality$new()

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("rank", {
  # tests for the property `rank` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`rank`, "EXPECTED_RESULT")
})

test_that("numGoTerms", {
  # tests for the property `numGoTerms` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numGoTerms`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})
