# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DifferentialExpressionAnalysisValueObject")

model_instance <- DifferentialExpressionAnalysisValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("factorValuesUsed", {
  # tests for the property `factorValuesUsed` (map(array[FactorValueValueObject]))

  # uncomment below to test the property
  #expect_equal(model.instance$`factorValuesUsed`, "EXPECTED_RESULT")
})

test_that("resultSets", {
  # tests for the property `resultSets` (array[DiffExResultSetSummaryValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`resultSets`, "EXPECTED_RESULT")
})

test_that("arrayDesignsUsed", {
  # tests for the property `arrayDesignsUsed` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`arrayDesignsUsed`, "EXPECTED_RESULT")
})

test_that("bioAssaySetId", {
  # tests for the property `bioAssaySetId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`bioAssaySetId`, "EXPECTED_RESULT")
})

test_that("sourceExperiment", {
  # tests for the property `sourceExperiment` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceExperiment`, "EXPECTED_RESULT")
})

test_that("subsetFactor", {
  # tests for the property `subsetFactor` (ExperimentalFactorValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`subsetFactor`, "EXPECTED_RESULT")
})

test_that("subsetFactorValue", {
  # tests for the property `subsetFactorValue` (FactorValueValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`subsetFactorValue`, "EXPECTED_RESULT")
})

test_that("subset", {
  # tests for the property `subset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`subset`, "EXPECTED_RESULT")
})
