# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeneProduct")

model_instance <- GeneProduct$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("previousNcbiId", {
  # tests for the property `previousNcbiId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`previousNcbiId`, "EXPECTED_RESULT")
})

test_that("physicalLocation", {
  # tests for the property `physicalLocation` (PhysicalLocation)

  # uncomment below to test the property
  #expect_equal(model.instance$`physicalLocation`, "EXPECTED_RESULT")
})

test_that("ncbiGi", {
  # tests for the property `ncbiGi` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ncbiGi`, "EXPECTED_RESULT")
})

test_that("accessions", {
  # tests for the property `accessions` (set[DatabaseEntry])

  # uncomment below to test the property
  #expect_equal(model.instance$`accessions`, "EXPECTED_RESULT")
})

test_that("exons", {
  # tests for the property `exons` (set[PhysicalLocation])

  # uncomment below to test the property
  #expect_equal(model.instance$`exons`, "EXPECTED_RESULT")
})

test_that("gene", {
  # tests for the property `gene` (Gene)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene`, "EXPECTED_RESULT")
})
