# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MeasurementValueObject")

model_instance <- MeasurementValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("unit", {
  # tests for the property `unit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`unit`, "EXPECTED_RESULT")
})

test_that("unitId", {
  # tests for the property `unitId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`unitId`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("representation", {
  # tests for the property `representation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`representation`, "EXPECTED_RESULT")
})
