# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BioAssayValueObject")

model_instance <- BioAssayValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("accession", {
  # tests for the property `accession` (DatabaseEntryValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("arrayDesign", {
  # tests for the property `arrayDesign` (ArrayDesignValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`arrayDesign`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("originalPlatform", {
  # tests for the property `originalPlatform` (ArrayDesignValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`originalPlatform`, "EXPECTED_RESULT")
})

test_that("outlier", {
  # tests for the property `outlier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`outlier`, "EXPECTED_RESULT")
})

test_that("predictedOutlier", {
  # tests for the property `predictedOutlier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`predictedOutlier`, "EXPECTED_RESULT")
})

test_that("processingDate", {
  # tests for the property `processingDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`processingDate`, "EXPECTED_RESULT")
})

test_that("sample", {
  # tests for the property `sample` (BioMaterialValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`sample`, "EXPECTED_RESULT")
})

test_that("sequencePairedReads", {
  # tests for the property `sequencePairedReads` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequencePairedReads`, "EXPECTED_RESULT")
})

test_that("sequenceReadCount", {
  # tests for the property `sequenceReadCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequenceReadCount`, "EXPECTED_RESULT")
})

test_that("sequenceReadLength", {
  # tests for the property `sequenceReadLength` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequenceReadLength`, "EXPECTED_RESULT")
})

test_that("userFlaggedOutlier", {
  # tests for the property `userFlaggedOutlier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userFlaggedOutlier`, "EXPECTED_RESULT")
})
