# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeneProductValueObject")

model_instance <- GeneProductValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("ncbiId", {
  # tests for the property `ncbiId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ncbiId`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("geneId", {
  # tests for the property `geneId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`geneId`, "EXPECTED_RESULT")
})

test_that("chromosome", {
  # tests for the property `chromosome` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chromosome`, "EXPECTED_RESULT")
})

test_that("strand", {
  # tests for the property `strand` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strand`, "EXPECTED_RESULT")
})

test_that("nucleotideStart", {
  # tests for the property `nucleotideStart` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotideStart`, "EXPECTED_RESULT")
})

test_that("nucleotideEnd", {
  # tests for the property `nucleotideEnd` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotideEnd`, "EXPECTED_RESULT")
})
