# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponseDataObjectListBioAssayValueObject")

model_instance <- ResponseDataObjectListBioAssayValueObject$new()

test_that("data", {
  # tests for the property `data` (array[BioAssayValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
