# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Keyword")

model_instance <- Keyword$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("isMajorTopic", {
  # tests for the property `isMajorTopic` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isMajorTopic`, "EXPECTED_RESULT")
})

test_that("term", {
  # tests for the property `term` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`term`, "EXPECTED_RESULT")
})
