# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BioSequence")

model_instance <- BioSequence$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("sequence", {
  # tests for the property `sequence` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence`, "EXPECTED_RESULT")
})

test_that("isApproximateLength", {
  # tests for the property `isApproximateLength` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isApproximateLength`, "EXPECTED_RESULT")
})

test_that("isCircular", {
  # tests for the property `isCircular` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isCircular`, "EXPECTED_RESULT")
})

test_that("polymerType", {
  # tests for the property `polymerType` (PolymerType)

  # uncomment below to test the property
  #expect_equal(model.instance$`polymerType`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (SequenceType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("fractionRepeats", {
  # tests for the property `fractionRepeats` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`fractionRepeats`, "EXPECTED_RESULT")
})

test_that("sequenceDatabaseEntry", {
  # tests for the property `sequenceDatabaseEntry` (DatabaseEntry)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequenceDatabaseEntry`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (Taxon)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("bioSequence2GeneProduct", {
  # tests for the property `bioSequence2GeneProduct` (set[BioSequence2GeneProduct])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioSequence2GeneProduct`, "EXPECTED_RESULT")
})
