# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayDesignValueObject")

model_instance <- ArrayDesignValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("lastUpdated", {
  # tests for the property `lastUpdated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastUpdated`, "EXPECTED_RESULT")
})

test_that("troubled", {
  # tests for the property `troubled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`troubled`, "EXPECTED_RESULT")
})

test_that("lastTroubledEvent", {
  # tests for the property `lastTroubledEvent` (AuditEventValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastTroubledEvent`, "EXPECTED_RESULT")
})

test_that("needsAttention", {
  # tests for the property `needsAttention` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`needsAttention`, "EXPECTED_RESULT")
})

test_that("lastNeedsAttentionEvent", {
  # tests for the property `lastNeedsAttentionEvent` (AuditEventValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastNeedsAttentionEvent`, "EXPECTED_RESULT")
})

test_that("curationNote", {
  # tests for the property `curationNote` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`curationNote`, "EXPECTED_RESULT")
})

test_that("lastNoteUpdateEvent", {
  # tests for the property `lastNoteUpdateEvent` (AuditEventValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastNoteUpdateEvent`, "EXPECTED_RESULT")
})

test_that("blackListed", {
  # tests for the property `blackListed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`blackListed`, "EXPECTED_RESULT")
})

test_that("color", {
  # tests for the property `color` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`color`, "EXPECTED_RESULT")
})

test_that("dateCached", {
  # tests for the property `dateCached` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dateCached`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("designElementCount", {
  # tests for the property `designElementCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`designElementCount`, "EXPECTED_RESULT")
})

test_that("expressionExperimentCount", {
  # tests for the property `expressionExperimentCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`expressionExperimentCount`, "EXPECTED_RESULT")
})

test_that("hasBlatAssociations", {
  # tests for the property `hasBlatAssociations` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hasBlatAssociations`, "EXPECTED_RESULT")
})

test_that("hasGeneAssociations", {
  # tests for the property `hasGeneAssociations` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hasGeneAssociations`, "EXPECTED_RESULT")
})

test_that("hasSequenceAssociations", {
  # tests for the property `hasSequenceAssociations` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hasSequenceAssociations`, "EXPECTED_RESULT")
})

test_that("isAffymetrixAltCdf", {
  # tests for the property `isAffymetrixAltCdf` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isAffymetrixAltCdf`, "EXPECTED_RESULT")
})

test_that("isMerged", {
  # tests for the property `isMerged` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isMerged`, "EXPECTED_RESULT")
})

test_that("isMergee", {
  # tests for the property `isMergee` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isMergee`, "EXPECTED_RESULT")
})

test_that("isSubsumed", {
  # tests for the property `isSubsumed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isSubsumed`, "EXPECTED_RESULT")
})

test_that("isSubsumer", {
  # tests for the property `isSubsumer` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isSubsumer`, "EXPECTED_RESULT")
})

test_that("lastGeneMapping", {
  # tests for the property `lastGeneMapping` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastGeneMapping`, "EXPECTED_RESULT")
})

test_that("lastRepeatMask", {
  # tests for the property `lastRepeatMask` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastRepeatMask`, "EXPECTED_RESULT")
})

test_that("lastSequenceAnalysis", {
  # tests for the property `lastSequenceAnalysis` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastSequenceAnalysis`, "EXPECTED_RESULT")
})

test_that("lastSequenceUpdate", {
  # tests for the property `lastSequenceUpdate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastSequenceUpdate`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("numGenes", {
  # tests for the property `numGenes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`numGenes`, "EXPECTED_RESULT")
})

test_that("numProbeAlignments", {
  # tests for the property `numProbeAlignments` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`numProbeAlignments`, "EXPECTED_RESULT")
})

test_that("numProbeSequences", {
  # tests for the property `numProbeSequences` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`numProbeSequences`, "EXPECTED_RESULT")
})

test_that("numProbesToGenes", {
  # tests for the property `numProbesToGenes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`numProbesToGenes`, "EXPECTED_RESULT")
})

test_that("shortName", {
  # tests for the property `shortName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`shortName`, "EXPECTED_RESULT")
})

test_that("switchedExpressionExperimentCount", {
  # tests for the property `switchedExpressionExperimentCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`switchedExpressionExperimentCount`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("taxonID", {
  # tests for the property `taxonID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonID`, "EXPECTED_RESULT")
})

test_that("technologyType", {
  # tests for the property `technologyType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`technologyType`, "EXPECTED_RESULT")
})

test_that("troubleDetails", {
  # tests for the property `troubleDetails` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`troubleDetails`, "EXPECTED_RESULT")
})
