# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExperimentalFactorValueObject")

model_instance <- ExperimentalFactorValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("categoryUri", {
  # tests for the property `categoryUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`categoryUri`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("factorValues", {
  # tests for the property `factorValues` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`factorValues`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("numValues", {
  # tests for the property `numValues` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numValues`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("values", {
  # tests for the property `values` (array[FactorValueValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`values`, "EXPECTED_RESULT")
})
