# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BioSequenceValueObject")

model_instance <- BioSequenceValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("fractionRepeats", {
  # tests for the property `fractionRepeats` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`fractionRepeats`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("sequence", {
  # tests for the property `sequence` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence`, "EXPECTED_RESULT")
})

test_that("sequenceDatabaseEntry", {
  # tests for the property `sequenceDatabaseEntry` (DatabaseEntryValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequenceDatabaseEntry`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (TaxonValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (SequenceType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
