# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExternalDatabase")

model_instance <- ExternalDatabase$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("localInstallDbName", {
  # tests for the property `localInstallDbName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`localInstallDbName`, "EXPECTED_RESULT")
})

test_that("webUri", {
  # tests for the property `webUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`webUri`, "EXPECTED_RESULT")
})

test_that("ftpUri", {
  # tests for the property `ftpUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ftpUri`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (DatabaseType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("databaseSupplier", {
  # tests for the property `databaseSupplier` (Contact)

  # uncomment below to test the property
  #expect_equal(model.instance$`databaseSupplier`, "EXPECTED_RESULT")
})
