# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PhenotypeAssociationPublication")

model_instance <- PhenotypeAssociationPublication$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("citation", {
  # tests for the property `citation` (BibliographicReference)

  # uncomment below to test the property
  #expect_equal(model.instance$`citation`, "EXPECTED_RESULT")
})
