# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SortValueObject")

model_instance <- SortValueObject$new()

test_that("orderBy", {
  # tests for the property `orderBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`orderBy`, "EXPECTED_RESULT")
})

test_that("direction", {
  # tests for the property `direction` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})
