# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ApiInfoValueObject")

model_instance <- ApiInfoValueObject$new()

test_that("welcome", {
  # tests for the property `welcome` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`welcome`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("docs", {
  # tests for the property `docs` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`docs`, "EXPECTED_RESULT")
})
