# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test QuantitationType")

model_instance <- QuantitationType$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("isBackground", {
  # tests for the property `isBackground` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isBackground`, "EXPECTED_RESULT")
})

test_that("isBackgroundSubtracted", {
  # tests for the property `isBackgroundSubtracted` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isBackgroundSubtracted`, "EXPECTED_RESULT")
})

test_that("isBatchCorrected", {
  # tests for the property `isBatchCorrected` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isBatchCorrected`, "EXPECTED_RESULT")
})

test_that("isMaskedPreferred", {
  # tests for the property `isMaskedPreferred` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isMaskedPreferred`, "EXPECTED_RESULT")
})

test_that("isNormalized", {
  # tests for the property `isNormalized` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isNormalized`, "EXPECTED_RESULT")
})

test_that("isPreferred", {
  # tests for the property `isPreferred` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isPreferred`, "EXPECTED_RESULT")
})

test_that("isRecomputedFromRawData", {
  # tests for the property `isRecomputedFromRawData` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isRecomputedFromRawData`, "EXPECTED_RESULT")
})

test_that("isRatio", {
  # tests for the property `isRatio` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isRatio`, "EXPECTED_RESULT")
})

test_that("generalType", {
  # tests for the property `generalType` (GeneralType)

  # uncomment below to test the property
  #expect_equal(model.instance$`generalType`, "EXPECTED_RESULT")
})

test_that("representation", {
  # tests for the property `representation` (PrimitiveType)

  # uncomment below to test the property
  #expect_equal(model.instance$`representation`, "EXPECTED_RESULT")
})

test_that("scale", {
  # tests for the property `scale` (ScaleType)

  # uncomment below to test the property
  #expect_equal(model.instance$`scale`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (StandardQuantitationType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
