# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DoubleMatrixLongInteger")

model_instance <- DoubleMatrixLongInteger$new()

test_that("colNames", {
  # tests for the property `colNames` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`colNames`, "EXPECTED_RESULT")
})

test_that("rowNames", {
  # tests for the property `rowNames` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`rowNames`, "EXPECTED_RESULT")
})

test_that("rawMatrix", {
  # tests for the property `rawMatrix` (array[array[numeric]])

  # uncomment below to test the property
  #expect_equal(model.instance$`rawMatrix`, "EXPECTED_RESULT")
})

test_that("columnNames", {
  # tests for the property `columnNames` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`columnNames`, "EXPECTED_RESULT")
})

test_that("rowNameMapIterator", {
  # tests for the property `rowNameMapIterator` (object)

  # uncomment below to test the property
  #expect_equal(model.instance$`rowNameMapIterator`, "EXPECTED_RESULT")
})
