# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BioMaterialValueObject")

model_instance <- BioMaterialValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("assayDescription", {
  # tests for the property `assayDescription` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assayDescription`, "EXPECTED_RESULT")
})

test_that("assayName", {
  # tests for the property `assayName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assayName`, "EXPECTED_RESULT")
})

test_that("bioAssays", {
  # tests for the property `bioAssays` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioAssays`, "EXPECTED_RESULT")
})

test_that("characteristics", {
  # tests for the property `characteristics` (array[CharacteristicValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`characteristics`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("factorIdToFactorValueId", {
  # tests for the property `factorIdToFactorValueId` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`factorIdToFactorValueId`, "EXPECTED_RESULT")
})

test_that("factors", {
  # tests for the property `factors` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`factors`, "EXPECTED_RESULT")
})

test_that("factorValueObjects", {
  # tests for the property `factorValueObjects` (array[IdentifiableValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`factorValueObjects`, "EXPECTED_RESULT")
})

test_that("factorValues", {
  # tests for the property `factorValues` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`factorValues`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("assayProcessingDate", {
  # tests for the property `assayProcessingDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assayProcessingDate`, "EXPECTED_RESULT")
})

test_that("characteristicValues", {
  # tests for the property `characteristicValues` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`characteristicValues`, "EXPECTED_RESULT")
})
