# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BioSequence2GeneProduct")

model_instance <- BioSequence2GeneProduct$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("sourceAnalysis", {
  # tests for the property `sourceAnalysis` (Analysis)

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceAnalysis`, "EXPECTED_RESULT")
})

test_that("overlap", {
  # tests for the property `overlap` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`overlap`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("threePrimeDistance", {
  # tests for the property `threePrimeDistance` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`threePrimeDistance`, "EXPECTED_RESULT")
})

test_that("threePrimeDistanceMeasurementMethod", {
  # tests for the property `threePrimeDistanceMeasurementMethod` (ThreePrimeDistanceMethod)

  # uncomment below to test the property
  #expect_equal(model.instance$`threePrimeDistanceMeasurementMethod`, "EXPECTED_RESULT")
})

test_that("specificity", {
  # tests for the property `specificity` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`specificity`, "EXPECTED_RESULT")
})

test_that("bioSequence", {
  # tests for the property `bioSequence` (BioSequence)

  # uncomment below to test the property
  #expect_equal(model.instance$`bioSequence`, "EXPECTED_RESULT")
})

test_that("geneProduct", {
  # tests for the property `geneProduct` (GeneProduct)

  # uncomment below to test the property
  #expect_equal(model.instance$`geneProduct`, "EXPECTED_RESULT")
})
