# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VectorElementValueObject")

model_instance <- VectorElementValueObject$new()

test_that("designElementName", {
  # tests for the property `designElementName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`designElementName`, "EXPECTED_RESULT")
})

test_that("bioAssayExpressionLevels", {
  # tests for the property `bioAssayExpressionLevels` (map(numeric))

  # uncomment below to test the property
  #expect_equal(model.instance$`bioAssayExpressionLevels`, "EXPECTED_RESULT")
})
