# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PhenotypeAssociation")

model_instance <- PhenotypeAssociation$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("auditTrail", {
  # tests for the property `auditTrail` (AuditTrail)

  # uncomment below to test the property
  #expect_equal(model.instance$`auditTrail`, "EXPECTED_RESULT")
})

test_that("evidenceCode", {
  # tests for the property `evidenceCode` (GOEvidenceCode)

  # uncomment below to test the property
  #expect_equal(model.instance$`evidenceCode`, "EXPECTED_RESULT")
})

test_that("isNegativeEvidence", {
  # tests for the property `isNegativeEvidence` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isNegativeEvidence`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("strength", {
  # tests for the property `strength` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`strength`, "EXPECTED_RESULT")
})

test_that("gene", {
  # tests for the property `gene` (Gene)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene`, "EXPECTED_RESULT")
})

test_that("phenotypes", {
  # tests for the property `phenotypes` (set[Characteristic])

  # uncomment below to test the property
  #expect_equal(model.instance$`phenotypes`, "EXPECTED_RESULT")
})

test_that("associationType", {
  # tests for the property `associationType` (Characteristic)

  # uncomment below to test the property
  #expect_equal(model.instance$`associationType`, "EXPECTED_RESULT")
})

test_that("evidenceSource", {
  # tests for the property `evidenceSource` (DatabaseEntry)

  # uncomment below to test the property
  #expect_equal(model.instance$`evidenceSource`, "EXPECTED_RESULT")
})

test_that("scoreType", {
  # tests for the property `scoreType` (QuantitationType)

  # uncomment below to test the property
  #expect_equal(model.instance$`scoreType`, "EXPECTED_RESULT")
})

test_that("phenotypeAssociationPublications", {
  # tests for the property `phenotypeAssociationPublications` (set[PhenotypeAssociationPublication])

  # uncomment below to test the property
  #expect_equal(model.instance$`phenotypeAssociationPublications`, "EXPECTED_RESULT")
})

test_that("mappingType", {
  # tests for the property `mappingType` (PhenotypeMappingType)

  # uncomment below to test the property
  #expect_equal(model.instance$`mappingType`, "EXPECTED_RESULT")
})

test_that("originalPhenotype", {
  # tests for the property `originalPhenotype` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`originalPhenotype`, "EXPECTED_RESULT")
})

test_that("relationship", {
  # tests for the property `relationship` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`relationship`, "EXPECTED_RESULT")
})

test_that("lastUpdated", {
  # tests for the property `lastUpdated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastUpdated`, "EXPECTED_RESULT")
})
