# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("GetApiInfo", {
  # tests for GetApiInfo
  # base path: /rest/v2
  # Retrieve an object with basic API information
  # @return [ResponseDataObjectApiInfoValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetAnnotations", {
  # tests for GetDatasetAnnotations
  # base path: /rest/v2
  # Retrieve the annotations analysis of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @return [ResponseDataObjectSetAnnotationValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetDesign", {
  # tests for GetDatasetDesign
  # base path: /rest/v2
  # Retrieve the design of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetDifferentialExpression", {
  # tests for GetDatasetDifferentialExpression
  # base path: /rest/v2
  # Retrieve the expression levels of a set of datasets subject to a threshold on their differential expressions
  # @param datasets array[GetResultSetsDatasetsParameterInner] 
  # @param diff_ex_set integer  (optional)
  # @param threshold numeric  (optional)
  # @param limit integer  (optional)
  # @param keep_non_specific character  (optional)
  # @param consolidate character  (optional)
  # @return [ResponseDataObjectListExperimentExpressionLevelsValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetDifferentialExpressionAnalyses", {
  # tests for GetDatasetDifferentialExpressionAnalyses
  # base path: /rest/v2
  # Retrieve the differential analyses of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @return [ResponseDataObjectListDifferentialExpressionAnalysisValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetDifferentialExpressionAnalysesResultSets", {
  # tests for GetDatasetDifferentialExpressionAnalysesResultSets
  # base path: /rest/v2
  # Retrieve the result sets of all differential analyses of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetExpression", {
  # tests for GetDatasetExpression
  # base path: /rest/v2
  # Retrieve the expression data of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @param filter character  (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetExpressionForGenes", {
  # tests for GetDatasetExpressionForGenes
  # base path: /rest/v2
  # Retrieve the expression data matrix of a set of datasets and genes
  # @param datasets array[GetResultSetsDatasetsParameterInner] 
  # @param genes array[GetDatasetExpressionForGenesGenesParameterInner] 
  # @param keep_non_specific character  (optional)
  # @param consolidate character  (optional)
  # @return [ResponseDataObjectListExperimentExpressionLevelsValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetExpressionPca", {
  # tests for GetDatasetExpressionPca
  # base path: /rest/v2
  # Retrieve the principal components (PCA) of a set of datasets
  # @param datasets array[GetResultSetsDatasetsParameterInner] 
  # @param component integer  (optional)
  # @param limit integer  (optional)
  # @param keep_non_specific character  (optional)
  # @param consolidate character  (optional)
  # @return [ResponseDataObjectListExperimentExpressionLevelsValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetPlatforms", {
  # tests for GetDatasetPlatforms
  # base path: /rest/v2
  # Retrieve the platform of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @return [ResponseDataObjectListArrayDesignValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetRawExpression", {
  # tests for GetDatasetRawExpression
  # base path: /rest/v2
  # Retrieve raw expression data of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetSamples", {
  # tests for GetDatasetSamples
  # base path: /rest/v2
  # Retrieve the samples of a dataset
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @return [ResponseDataObjectListBioAssayValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetSvd", {
  # tests for GetDatasetSvd
  # base path: /rest/v2
  # Retrieve the singular value decomposition (SVD) of a dataset expression data
  # @param dataset GetResultSetsDatasetsParameterInner 
  # @return [ResponseDataObjectSimpleSVDValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasets", {
  # tests for GetDatasets
  # base path: /rest/v2
  # Retrieve all datasets
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectExpressionExperimentValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetsByIds", {
  # tests for GetDatasetsByIds
  # base path: /rest/v2
  # Retrieve datasets by their identifiers
  # @param dataset array[GetResultSetsDatasetsParameterInner] 
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectExpressionExperimentValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGeneGeneCoexpression", {
  # tests for GetGeneGeneCoexpression
  # base path: /rest/v2
  # Retrieve the coexpression of two given genes
  # @param gene GetDatasetExpressionForGenesGenesParameterInner 
  # @param with GetDatasetExpressionForGenesGenesParameterInner  (optional)
  # @param limit integer  (optional)
  # @param stringency integer  (optional)
  # @return [ResponseDataObjectListCoexpressionValueObjectExt]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGeneGoTerms", {
  # tests for GetGeneGoTerms
  # base path: /rest/v2
  # Retrieve the GO terms associated to a gene
  # @param gene GetDatasetExpressionForGenesGenesParameterInner 
  # @return [ResponseDataObjectListGeneOntologyTermValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGeneLocations", {
  # tests for GetGeneLocations
  # base path: /rest/v2
  # Retrieve the physical locations of a given gene
  # @param gene GetDatasetExpressionForGenesGenesParameterInner 
  # @return [ResponseDataObjectListPhysicalLocationValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGeneLocationsInTaxon", {
  # tests for GetGeneLocationsInTaxon
  # base path: /rest/v2
  # Retrieve physical locations for a given gene and taxon
  # @param taxon SearchTaxonDatasetsTaxonParameter 
  # @param gene GetDatasetExpressionForGenesGenesParameterInner 
  # @return [ResponseDataObjectListPhysicalLocationValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGeneProbes", {
  # tests for GetGeneProbes
  # base path: /rest/v2
  # Retrieve the probes associated to a genes
  # @param gene GetDatasetExpressionForGenesGenesParameterInner 
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @return [PaginatedResponseDataObjectCompositeSequenceValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGenes", {
  # tests for GetGenes
  # base path: /rest/v2
  # Retrieve genes matching a gene identifier
  # @param genes array[GetDatasetExpressionForGenesGenesParameterInner] 
  # @return [ResponseDataObjectListGeneValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlatformAnnotations", {
  # tests for GetPlatformAnnotations
  # base path: /rest/v2
  # Retrieve the annotations of a given platform
  # @param platform GetPlatformAnnotationsPlatformParameter 
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlatformDatasets", {
  # tests for GetPlatformDatasets
  # base path: /rest/v2
  # Retrieve all experiments within a given platform
  # @param platform GetPlatformAnnotationsPlatformParameter 
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @return [PaginatedResponseDataObjectExpressionExperimentValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlatformElement", {
  # tests for GetPlatformElement
  # base path: /rest/v2
  # Retrieve the selected composite sequences for a given platform
  # @param platform GetPlatformAnnotationsPlatformParameter 
  # @param probes array[GetPlatformElementProbesParameterInner] 
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @return [PaginatedResponseDataObjectCompositeSequenceValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlatformElementGenes", {
  # tests for GetPlatformElementGenes
  # base path: /rest/v2
  # Retrieve the genes associated to a probe in a given platform
  # @param platform GetPlatformAnnotationsPlatformParameter 
  # @param probe GetPlatformElementProbesParameterInner 
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @return [PaginatedResponseDataObjectGeneValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlatformElements", {
  # tests for GetPlatformElements
  # base path: /rest/v2
  # Retrieve the composite sequences for a given platform
  # @param platform GetPlatformAnnotationsPlatformParameter 
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @return [PaginatedResponseDataObjectCompositeSequenceValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlatforms", {
  # tests for GetPlatforms
  # base path: /rest/v2
  # Retrieve all platforms
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectArrayDesignValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlatformsByIds", {
  # tests for GetPlatformsByIds
  # base path: /rest/v2
  # Retrieve all platforms matching a set of platform identifiers
  # @param platform array[GetPlatformAnnotationsPlatformParameter] 
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectArrayDesignValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetResultSet", {
  # tests for GetResultSet
  # base path: /rest/v2
  # Retrieve a single analysis result set by its identifier
  # @param result_set integer 
  # @return [ResponseDataObjectExpressionAnalysisResultSetValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetResultSetAsTsv", {
  # tests for GetResultSetAsTsv
  # base path: /rest/v2
  # Retrieve a single analysis result set by its identifier as a tab-separated values
  # @param result_set_ integer 
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetResultSets", {
  # tests for GetResultSets
  # base path: /rest/v2
  # Retrieve all result sets matching the provided criteria
  # @param datasets array[GetResultSetsDatasetsParameterInner]  (optional)
  # @param database_entries array[GetResultSetsDatabaseEntriesParameterInner]  (optional)
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectExpressionAnalysisResultSetValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTaxa", {
  # tests for GetTaxa
  # base path: /rest/v2
  # Retrieve all available taxa
  # @return [ResponseDataObjectListTaxonValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTaxaByIds", {
  # tests for GetTaxaByIds
  # base path: /rest/v2
  # Retrieve taxa by their identifiers
  # @param taxa array[SearchTaxonDatasetsTaxonParameter] 
  # @return [ResponseDataObjectListTaxonValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTaxonDatasets", {
  # tests for GetTaxonDatasets
  # base path: /rest/v2
  # Retrieve the datasets for a given taxon
  # @param taxon SearchTaxonDatasetsTaxonParameter 
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectExpressionExperimentValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTaxonGenes", {
  # tests for GetTaxonGenes
  # base path: /rest/v2
  # Retrieve all genes in a given taxon
  # @param taxon SearchTaxonDatasetsTaxonParameter 
  # @param gene GetDatasetExpressionForGenesGenesParameterInner 
  # @return [ResponseDataObjectListGeneValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTaxonGenesOverlappingChromosome", {
  # tests for GetTaxonGenesOverlappingChromosome
  # base path: /rest/v2
  # Retrieve genes overlapping a given region in a taxon
  # @param taxon SearchTaxonDatasetsTaxonParameter 
  # @param chromosome character 
  # @param strand character  (optional)
  # @param start integer  (optional)
  # @param size integer  (optional)
  # @return [ResponseDataObjectListGeneValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Search", {
  # tests for Search
  # base path: /rest/v2
  # Search everything in Gemma.
  # @param query character  (optional)
  # @param taxon SearchTaxonDatasetsTaxonParameter  (optional)
  # @param platform GetPlatformAnnotationsPlatformParameter  (optional)
  # @param result_types array[character]  (optional)
  # @param limit integer  (optional)
  # @return [SearchResultsResponseDataObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchAnnotations", {
  # tests for SearchAnnotations
  # base path: /rest/v2
  # Search for annotation tags
  # @param query array[character] 
  # @return [ResponseDataObjectListAnnotationSearchResultValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchDatasets", {
  # tests for SearchDatasets
  # base path: /rest/v2
  # Retrieve datasets associated to an annotation tags search
  # @param query array[character] 
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectExpressionExperimentValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchTaxonDatasets", {
  # tests for SearchTaxonDatasets
  # base path: /rest/v2
  # Retrieve datasets within a given taxa associated to an annotation tags search
  # @param taxon SearchTaxonDatasetsTaxonParameter 
  # @param query array[character] 
  # @param filter character  (optional)
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @return [PaginatedResponseDataObjectExpressionExperimentValueObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
