# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Gene")

model_instance <- Gene$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("previousNcbiId", {
  # tests for the property `previousNcbiId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`previousNcbiId`, "EXPECTED_RESULT")
})

test_that("physicalLocation", {
  # tests for the property `physicalLocation` (PhysicalLocation)

  # uncomment below to test the property
  #expect_equal(model.instance$`physicalLocation`, "EXPECTED_RESULT")
})

test_that("officialSymbol", {
  # tests for the property `officialSymbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`officialSymbol`, "EXPECTED_RESULT")
})

test_that("officialName", {
  # tests for the property `officialName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`officialName`, "EXPECTED_RESULT")
})

test_that("ncbiGeneId", {
  # tests for the property `ncbiGeneId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ncbiGeneId`, "EXPECTED_RESULT")
})

test_that("ensemblId", {
  # tests for the property `ensemblId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ensemblId`, "EXPECTED_RESULT")
})

test_that("products", {
  # tests for the property `products` (set[GeneProduct])

  # uncomment below to test the property
  #expect_equal(model.instance$`products`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (set[GeneAlias])

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (Taxon)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("accessions", {
  # tests for the property `accessions` (set[DatabaseEntry])

  # uncomment below to test the property
  #expect_equal(model.instance$`accessions`, "EXPECTED_RESULT")
})

test_that("multifunctionality", {
  # tests for the property `multifunctionality` (Multifunctionality)

  # uncomment below to test the property
  #expect_equal(model.instance$`multifunctionality`, "EXPECTED_RESULT")
})

test_that("phenotypeAssociations", {
  # tests for the property `phenotypeAssociations` (set[PhenotypeAssociation])

  # uncomment below to test the property
  #expect_equal(model.instance$`phenotypeAssociations`, "EXPECTED_RESULT")
})
