# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test User")

model_instance <- User$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("lastName", {
  # tests for the property `lastName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastName`, "EXPECTED_RESULT")
})

test_that("userName", {
  # tests for the property `userName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userName`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

test_that("passwordHint", {
  # tests for the property `passwordHint` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`passwordHint`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})

test_that("signupToken", {
  # tests for the property `signupToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`signupToken`, "EXPECTED_RESULT")
})

test_that("signupTokenDatestamp", {
  # tests for the property `signupTokenDatestamp` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`signupTokenDatestamp`, "EXPECTED_RESULT")
})

test_that("jobs", {
  # tests for the property `jobs` (set[JobInfo])

  # uncomment below to test the property
  #expect_equal(model.instance$`jobs`, "EXPECTED_RESULT")
})

test_that("fullName", {
  # tests for the property `fullName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fullName`, "EXPECTED_RESULT")
})
