# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeneSetValueObject")

model_instance <- GeneSetValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("geneIds", {
  # tests for the property `geneIds` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`geneIds`, "EXPECTED_RESULT")
})

test_that("isPublic", {
  # tests for the property `isPublic` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isPublic`, "EXPECTED_RESULT")
})

test_that("isShared", {
  # tests for the property `isShared` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isShared`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("taxonId", {
  # tests for the property `taxonId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonId`, "EXPECTED_RESULT")
})

test_that("taxonName", {
  # tests for the property `taxonName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonName`, "EXPECTED_RESULT")
})

test_that("userOwned", {
  # tests for the property `userOwned` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userOwned`, "EXPECTED_RESULT")
})

test_that("userCanWrite", {
  # tests for the property `userCanWrite` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userCanWrite`, "EXPECTED_RESULT")
})
