# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CoexpressionValueObjectExt")

model_instance <- CoexpressionValueObjectExt$new()

test_that("containsMyData", {
  # tests for the property `containsMyData` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`containsMyData`, "EXPECTED_RESULT")
})

test_that("foundGene", {
  # tests for the property `foundGene` (GeneValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`foundGene`, "EXPECTED_RESULT")
})

test_that("foundGeneNodeDegree", {
  # tests for the property `foundGeneNodeDegree` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`foundGeneNodeDegree`, "EXPECTED_RESULT")
})

test_that("foundGeneNodeDegreeRank", {
  # tests for the property `foundGeneNodeDegreeRank` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`foundGeneNodeDegreeRank`, "EXPECTED_RESULT")
})

test_that("negSupp", {
  # tests for the property `negSupp` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`negSupp`, "EXPECTED_RESULT")
})

test_that("numTestedIn", {
  # tests for the property `numTestedIn` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numTestedIn`, "EXPECTED_RESULT")
})

test_that("posSupp", {
  # tests for the property `posSupp` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`posSupp`, "EXPECTED_RESULT")
})

test_that("queryGene", {
  # tests for the property `queryGene` (GeneValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`queryGene`, "EXPECTED_RESULT")
})

test_that("queryGeneNodeDegree", {
  # tests for the property `queryGeneNodeDegree` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`queryGeneNodeDegree`, "EXPECTED_RESULT")
})

test_that("queryGeneNodeDegreeRank", {
  # tests for the property `queryGeneNodeDegreeRank` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`queryGeneNodeDegreeRank`, "EXPECTED_RESULT")
})

test_that("sortKey", {
  # tests for the property `sortKey` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sortKey`, "EXPECTED_RESULT")
})

test_that("supportingExperiments", {
  # tests for the property `supportingExperiments` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`supportingExperiments`, "EXPECTED_RESULT")
})

test_that("support", {
  # tests for the property `support` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`support`, "EXPECTED_RESULT")
})
