# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayDesign")

model_instance <- ArrayDesign$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("auditTrail", {
  # tests for the property `auditTrail` (AuditTrail)

  # uncomment below to test the property
  #expect_equal(model.instance$`auditTrail`, "EXPECTED_RESULT")
})

test_that("advertisedNumberOfDesignElements", {
  # tests for the property `advertisedNumberOfDesignElements` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`advertisedNumberOfDesignElements`, "EXPECTED_RESULT")
})

test_that("alternateNames", {
  # tests for the property `alternateNames` (set[AlternateName])

  # uncomment below to test the property
  #expect_equal(model.instance$`alternateNames`, "EXPECTED_RESULT")
})

test_that("alternativeTo", {
  # tests for the property `alternativeTo` (ArrayDesign)

  # uncomment below to test the property
  #expect_equal(model.instance$`alternativeTo`, "EXPECTED_RESULT")
})

test_that("compositeSequences", {
  # tests for the property `compositeSequences` (set[CompositeSequence])

  # uncomment below to test the property
  #expect_equal(model.instance$`compositeSequences`, "EXPECTED_RESULT")
})

test_that("curationDetails", {
  # tests for the property `curationDetails` (CurationDetails)

  # uncomment below to test the property
  #expect_equal(model.instance$`curationDetails`, "EXPECTED_RESULT")
})

test_that("designProvider", {
  # tests for the property `designProvider` (Contact)

  # uncomment below to test the property
  #expect_equal(model.instance$`designProvider`, "EXPECTED_RESULT")
})

test_that("externalReferences", {
  # tests for the property `externalReferences` (set[DatabaseEntry])

  # uncomment below to test the property
  #expect_equal(model.instance$`externalReferences`, "EXPECTED_RESULT")
})

test_that("mergedInto", {
  # tests for the property `mergedInto` (ArrayDesign)

  # uncomment below to test the property
  #expect_equal(model.instance$`mergedInto`, "EXPECTED_RESULT")
})

test_that("mergees", {
  # tests for the property `mergees` (set[ArrayDesign])

  # uncomment below to test the property
  #expect_equal(model.instance$`mergees`, "EXPECTED_RESULT")
})

test_that("primaryTaxon", {
  # tests for the property `primaryTaxon` (Taxon)

  # uncomment below to test the property
  #expect_equal(model.instance$`primaryTaxon`, "EXPECTED_RESULT")
})

test_that("shortName", {
  # tests for the property `shortName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`shortName`, "EXPECTED_RESULT")
})

test_that("subsumedArrayDesigns", {
  # tests for the property `subsumedArrayDesigns` (set[ArrayDesign])

  # uncomment below to test the property
  #expect_equal(model.instance$`subsumedArrayDesigns`, "EXPECTED_RESULT")
})

test_that("subsumingArrayDesign", {
  # tests for the property `subsumingArrayDesign` (ArrayDesign)

  # uncomment below to test the property
  #expect_equal(model.instance$`subsumingArrayDesign`, "EXPECTED_RESULT")
})

test_that("technologyType", {
  # tests for the property `technologyType` (TechnologyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`technologyType`, "EXPECTED_RESULT")
})
