# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FactorValueBasicValueObject")

model_instance <- FactorValueBasicValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("characteristics", {
  # tests for the property `characteristics` (array[CharacteristicBasicValueObject])

  # uncomment below to test the property
  #expect_equal(model.instance$`characteristics`, "EXPECTED_RESULT")
})

test_that("experimentalFactorCategory", {
  # tests for the property `experimentalFactorCategory` (CharacteristicBasicValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`experimentalFactorCategory`, "EXPECTED_RESULT")
})

test_that("measurement", {
  # tests for the property `measurement` (MeasurementValueObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`measurement`, "EXPECTED_RESULT")
})

test_that("fvValue", {
  # tests for the property `fvValue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fvValue`, "EXPECTED_RESULT")
})

test_that("fvSummary", {
  # tests for the property `fvSummary` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fvSummary`, "EXPECTED_RESULT")
})

test_that("experimentalFactorId", {
  # tests for the property `experimentalFactorId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`experimentalFactorId`, "EXPECTED_RESULT")
})

test_that("baseline", {
  # tests for the property `baseline` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`baseline`, "EXPECTED_RESULT")
})
