# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobInfo")

model_instance <- JobInfo$new()

test_that("runningStatus", {
  # tests for the property `runningStatus` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`runningStatus`, "EXPECTED_RESULT")
})

test_that("failedMessage", {
  # tests for the property `failedMessage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`failedMessage`, "EXPECTED_RESULT")
})

test_that("startTime", {
  # tests for the property `startTime` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`startTime`, "EXPECTED_RESULT")
})

test_that("endTime", {
  # tests for the property `endTime` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`endTime`, "EXPECTED_RESULT")
})

test_that("phases", {
  # tests for the property `phases` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`phases`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("messages", {
  # tests for the property `messages` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`messages`, "EXPECTED_RESULT")
})

test_that("taskId", {
  # tests for the property `taskId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taskId`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("user", {
  # tests for the property `user` (User)

  # uncomment below to test the property
  #expect_equal(model.instance$`user`, "EXPECTED_RESULT")
})
