# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuditTrail")

model_instance <- AuditTrail$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("events", {
  # tests for the property `events` (array[AuditEvent])

  # uncomment below to test the property
  #expect_equal(model.instance$`events`, "EXPECTED_RESULT")
})

test_that("creationEvent", {
  # tests for the property `creationEvent` (AuditEvent)

  # uncomment below to test the property
  #expect_equal(model.instance$`creationEvent`, "EXPECTED_RESULT")
})

test_that("last", {
  # tests for the property `last` (AuditEvent)

  # uncomment below to test the property
  #expect_equal(model.instance$`last`, "EXPECTED_RESULT")
})
