# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Chromosome")

model_instance <- Chromosome$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("assemblyDatabase", {
  # tests for the property `assemblyDatabase` (ExternalDatabase)

  # uncomment below to test the property
  #expect_equal(model.instance$`assemblyDatabase`, "EXPECTED_RESULT")
})

test_that("sequence", {
  # tests for the property `sequence` (BioSequence)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (Taxon)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})
