# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WellComposedErrorBody")

model_instance <- WellComposedErrorBody$new()

test_that("code", {
  # tests for the property `code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})
