# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Taxon")

model_instance <- Taxon$new()

test_that("scientificName", {
  # tests for the property `scientificName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`scientificName`, "EXPECTED_RESULT")
})

test_that("commonName", {
  # tests for the property `commonName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commonName`, "EXPECTED_RESULT")
})

test_that("ncbiId", {
  # tests for the property `ncbiId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ncbiId`, "EXPECTED_RESULT")
})

test_that("isGenesUsable", {
  # tests for the property `isGenesUsable` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isGenesUsable`, "EXPECTED_RESULT")
})

test_that("secondaryNcbiId", {
  # tests for the property `secondaryNcbiId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`secondaryNcbiId`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("externalDatabase", {
  # tests for the property `externalDatabase` (ExternalDatabase)

  # uncomment below to test the property
  #expect_equal(model.instance$`externalDatabase`, "EXPECTED_RESULT")
})
