# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CharacteristicValueObject")

model_instance <- CharacteristicValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("urlId", {
  # tests for the property `urlId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`urlId`, "EXPECTED_RESULT")
})

test_that("alreadyPresentInDatabase", {
  # tests for the property `alreadyPresentInDatabase` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`alreadyPresentInDatabase`, "EXPECTED_RESULT")
})

test_that("alreadyPresentOnGene", {
  # tests for the property `alreadyPresentOnGene` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`alreadyPresentOnGene`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("categoryUri", {
  # tests for the property `categoryUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`categoryUri`, "EXPECTED_RESULT")
})

test_that("child", {
  # tests for the property `child` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`child`, "EXPECTED_RESULT")
})

test_that("numTimesUsed", {
  # tests for the property `numTimesUsed` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numTimesUsed`, "EXPECTED_RESULT")
})

test_that("ontologyUsed", {
  # tests for the property `ontologyUsed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ontologyUsed`, "EXPECTED_RESULT")
})

test_that("privateGeneCount", {
  # tests for the property `privateGeneCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`privateGeneCount`, "EXPECTED_RESULT")
})

test_that("publicGeneCount", {
  # tests for the property `publicGeneCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`publicGeneCount`, "EXPECTED_RESULT")
})

test_that("root", {
  # tests for the property `root` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`root`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("valueUri", {
  # tests for the property `valueUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`valueUri`, "EXPECTED_RESULT")
})
