# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FactorValueValueObject")

model_instance <- FactorValueValueObject$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("categoryUri", {
  # tests for the property `categoryUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`categoryUri`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("valueUri", {
  # tests for the property `valueUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`valueUri`, "EXPECTED_RESULT")
})

test_that("charId", {
  # tests for the property `charId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`charId`, "EXPECTED_RESULT")
})

test_that("factorId", {
  # tests for the property `factorId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`factorId`, "EXPECTED_RESULT")
})

test_that("isBaseline", {
  # tests for the property `isBaseline` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isBaseline`, "EXPECTED_RESULT")
})

test_that("measurement", {
  # tests for the property `measurement` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`measurement`, "EXPECTED_RESULT")
})

test_that("factorValue", {
  # tests for the property `factorValue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`factorValue`, "EXPECTED_RESULT")
})
